-- Creates a table with the sum of the minutes watched grouped by user and program
CREATE TABLE T_PROGRAM_RECOMMENDATION AS
SELECT BOX_ID, PROGRAM_NAME, SUM(DURATION_MIN)
FROM T_PYTHON_EVENTS
GROUP BY BOX_ID, PROGRAM_NAME

-- Normalizes the rating
CREATE TABLE T_PROG_RECOMMENDATION AS
SELECT VAL.BOX_ID, PROGRAM_NAME, ((RATING / MAXIMUM) * 5) AS NORM_RATING 
FROM T_PROGRAM_RECOMMENDATION VAL
INNER JOIN (SELECT MAX(RATING) MAXIMUM, BOX_ID
	        FROM T_PROGRAM_RECOMMENDATION
            GROUP BY BOX_ID) MAXE ON MAXE.BOX_ID = VAL.BOX_ID
ORDER BY BOX_ID DESC
